In [44]:
import numpy as np
import pandas as pd 

# 1. Create a 3x3x3 array with random values 

In [5]:
a = np.random.randint(0,100,size=(3,3,3))
a

array([[[71, 51, 65],
        [60, 70, 91],
        [45, 79, 83]],

       [[16, 75,  6],
        [ 8, 86, 11],
        [26, 40, 32]],

       [[22, 93, 44],
        [62, 46, 41],
        [98, 28, 47]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
a2 = np.diag(np.arange(1,5),k = -1)
a2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
a3 = np.zeros((8,8),dtype = int)
a3[1::2,::2] = 1
a3[::2,1::2] = 1
a3

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [31]:
a4 = np.random.random((5,5))
a4

array([[0.91102112, 0.5167453 , 0.41569881, 0.69237466, 0.84381775],
       [0.47640401, 0.91060653, 0.22559391, 0.02417552, 0.39236554],
       [0.20942373, 0.73582391, 0.96243841, 0.40999994, 0.08454093],
       [0.59480552, 0.27389016, 0.85905948, 0.92312105, 0.89521512],
       [0.90902914, 0.02214922, 0.93663377, 0.02641687, 0.83147075]])

In [32]:
amin , amax = a4.min() ,a4.max()
a4 = (a4 - amin) / (amax - amin)
a4

array([[0.94531758, 0.52600422, 0.41854101, 0.7127865 , 0.87384662],
       [0.48310115, 0.94487666, 0.21636396, 0.00215498, 0.39372602],
       [0.19916694, 0.7589949 , 1.        , 0.41248025, 0.06635375],
       [0.60902147, 0.26772715, 0.89005624, 0.95818589, 0.92850785],
       [0.9431991 , 0.        , 0.9725567 , 0.00453867, 0.86071555]])

# 5.  How to find common values between two arrays?

In [40]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
a1, a2

(array([8, 3, 6, 5, 9, 3, 3, 6, 8, 9]), array([3, 4, 5, 7, 1, 8, 7, 9, 6, 5]))

In [41]:
np.intersect1d(a1,a2)

array([3, 5, 6, 8, 9])

# 6.How to get the dates of yesterday, today and tomorrow?

In [49]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
yesterday

numpy.datetime64('2020-07-24')

In [48]:
today = np.datetime64('today','D')
today

numpy.datetime64('2020-07-25')

In [50]:
tommorow = np.datetime64('today','D') + np.timedelta64(1,'D')
tommorow

numpy.datetime64('2020-07-26')

# 7. Consider two random array A and B, check if they are equal

In [52]:
a1 = np.random.randint(0,2,5)
a2 = np.random.randint(0,2,5)
is_eql = np.array_equal(a1,a2)
is_eql

False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [53]:
v = np.random.randint(0,10,10)
v

array([0, 0, 8, 9, 6, 7, 4, 5, 9, 7])

In [55]:
v[v.argmax()] = 0
v

array([0, 0, 8, 0, 6, 7, 4, 5, 9, 7])

# 9. How to print all the values of an array?

In [60]:
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 10.Subtract the mean of each row of a matrix

In [62]:
a = np.random.rand(5,5)
a

array([[0.64750729, 0.45879303, 0.12372588, 0.89234865, 0.39075808],
       [0.81537741, 0.40142626, 0.78700192, 0.6213974 , 0.92102537],
       [0.45637104, 0.38179207, 0.45466585, 0.98378898, 0.95131216],
       [0.95146587, 0.02826014, 0.91390224, 0.18362549, 0.28131771],
       [0.49263437, 0.50220562, 0.80070434, 0.06709975, 0.64932497]])

In [65]:
a = a - a.mean(axis = 1 , keepdims = True )
a

array([[ 1.44880699e-01, -4.38335565e-02, -3.78900706e-01,
         3.89722067e-01, -1.11868504e-01],
       [ 1.06131735e-01, -3.07819409e-01,  7.77562503e-02,
        -8.78482747e-02,  2.11779698e-01],
       [-1.89214983e-01, -2.63793952e-01, -1.90920171e-01,
         3.38202963e-01,  3.05726143e-01],
       [ 4.79751575e-01, -4.43454148e-01,  4.42187948e-01,
        -2.88088798e-01, -1.90396577e-01],
       [-9.75944499e-03, -1.88189565e-04,  2.98310533e-01,
        -4.35294058e-01,  1.46931159e-01]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [76]:
Z = np.zeros(10)

I = np.random.randint(0,len(Z),20)
Z, I

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([3, 9, 8, 1, 1, 6, 7, 5, 0, 8, 3, 0, 9, 1, 6, 6, 2, 9, 3, 0]))

In [77]:
np.add.at(Z,I,1)
Z

array([3., 3., 1., 3., 0., 1., 3., 1., 2., 3.])

# 12.How to get the diagonal of a dot product?

In [84]:
a = np.random.randint(1,10,(5,5))
b = np.random.randint(1,10,(5,5))
np.diag(np.dot(a,b))

array([176, 145,  82, 186, 135])

# 13.How to find the most frequent value in an array?

In [91]:
a = np.random.randint(0,20,50)
print(np.bincount(a).argmax())

15


# 14.How to get the n largest values of an array

In [99]:
a = np.random.randint(0,75,50)
n = 5
b = np.argsort(a)
a[b[-n:]]

array([68, 70, 71, 72, 73])


# 15.How to create a record array from a regular array?

In [100]:
Z = np.array([("Hello", 2.5, 3),
             ("World", 3.6, 2)])

R = np.core.records.fromarrays(Z.T, names='col1, col2, col3',formats = 'S8, f8, i8')

print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
